export type ResponseHandlerType = "success-code"
    |"error-code"
    |"content-type"
    |"header"
    |"rendered-template"
    |"redirect"
    |"location"
    |"on-empty"
    |"on-null"
    |"on-undefined"
    |"text-response"
    |"json-response"
    |"response-class-transform-options";